//
//  MobileNetVietnameseOverrides.swift
//  KidX
//
//  Curated child-friendly Vietnamese names for animal, bird, and fish labels.
//

import Foundation

enum MobileNetVietnameseOverrides {
    static let values: [String: String] = [
        "tench, Tinca tinca": "cá tench",
        "brambling, Fringilla montifringilla": "chim sẻ phương bắc",
        "goldfinch, Carduelis carduelis": "chim sẻ vàng",
        "house finch, linnet, Carpodacus mexicanus": "chim sẻ nhà",
        "junco, snowbird": "chim sẻ tuyết",
        "indigo bunting, indigo finch, indigo bird, Passerina cyanea": "chim sẻ chàm",
        "robin, American robin, Turdus migratorius": "chim cổ đỏ Mỹ",
        "bulbul": "chim chào mào",
        "jay": "chim giẻ cùi",
        "magpie": "chim ác là",
        "chickadee": "chim bạc má nhỏ",
        "water ouzel, dipper": "chim lặn suối",
        "kite": "diều hâu",
        "European fire salamander, Salamandra salamandra": "kỳ giông lửa châu Âu",
        "common newt, Triturus vulgaris": "sa giông thường",
        "eft": "sa giông non",
        "spotted salamander, Ambystoma maculatum": "kỳ giông đốm",
        "axolotl, mud puppy, Ambystoma mexicanum": "kỳ giông axolotl",
        "tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui": "ếch đuôi",
        "banded gecko": "tắc kè vằn",
        "whiptail, whiptail lizard": "thằn lằn đuôi roi",
        "agama": "thằn lằn agama",
        "frilled lizard, Chlamydosaurus kingi": "thằn lằn cổ diềm",
        "alligator lizard": "thằn lằn cá sấu",
        "Gila monster, Heloderma suspectum": "thằn lằn Gila",
        "green lizard, Lacerta viridis": "thằn lằn xanh",
        "African chameleon, Chamaeleo chamaeleon": "tắc kè hoa châu Phi",
        "thunder snake, worm snake, Carphophis amoenus": "rắn giun",
        "ringneck snake, ring-necked snake, ring snake": "rắn cổ khoang",
        "hognose snake, puff adder, sand viper": "rắn mũi lợn",
        "green snake, grass snake": "rắn cỏ xanh",
        "king snake, kingsnake": "rắn vua",
        "garter snake, grass snake": "rắn sọc",
        "water snake": "rắn nước",
        "vine snake": "rắn roi xanh",
        "night snake, Hypsiglena torquata": "rắn đêm",
        "horned viper, cerastes, sand viper, horned asp, Cerastes cornutus": "rắn lục sừng",
        "harvestman, daddy longlegs, Phalangium opilio": "nhện chân dài",
        "black and gold garden spider, Argiope aurantia": "nhện vườn vàng đen",
        "barn spider, Araneus cavaticus": "nhện nhà kho",
        "garden spider, Aranea diademata": "nhện vườn",
        "black widow, Latrodectus mactans": "nhện góa phụ đen",
        "wolf spider, hunting spider": "nhện sói",
        "black grouse": "gà gô đen",
        "ptarmigan": "gà gô tuyết",
        "ruffed grouse, partridge, Bonasa umbellus": "gà gô cổ xù",
        "prairie chicken, prairie grouse, prairie fowl": "gà đồng cỏ",
        "partridge": "chim đa đa",
        "sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita": "vẹt mào vàng",
        "lorikeet": "vẹt hút mật",
        "coucal": "chim bìm bịp",
        "bee eater": "chim ăn ong",
        "hornbill": "chim hồng hoàng",
        "jacamar": "chim jacamar",
        "red-breasted merganser, Mergus serrator": "vịt biển mào đỏ",
        "flatworm, platyhelminth": "giun dẹp",
        "nematode, nematode worm, roundworm": "giun tròn",
        "conch": "ốc xà cừ",
        "chiton, coat-of-mail shell, sea cradle, polyplacophore": "ốc nhiều mảnh",
        "Dungeness crab, Cancer magister": "cua Dungeness",
        "rock crab, Cancer irroratus": "cua đá",
        "fiddler crab": "cua gọi",
        "king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica": "cua hoàng đế",
        "spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish": "tôm hùm gai",
        "hermit crab": "cua ẩn sĩ",
        "isopod": "bọ chân đều",
        "white stork, Ciconia ciconia": "cò trắng",
        "black stork, Ciconia nigra": "cò đen",
        "spoonbill": "cò thìa",
        "little blue heron, Egretta caerulea": "diệc xanh nhỏ",
        "American egret, great white heron, Egretta albus": "cò trắng lớn",
        "bittern": "cò lạo",
        "crane": "chim hạc",
        "limpkin, Aramus pictus": "chim limpkin",
        "European gallinule, Porphyrio porphyrio": "gà nước tím",
        "American coot, marsh hen, mud hen, water hen, Fulica americana": "gà nước Mỹ",
        "bustard": "chim ô tác",
        "ruddy turnstone, Arenaria interpres": "chim lật đá",
        "red-backed sandpiper, dunlin, Erolia alpina": "chim choắt lưng đỏ",
        "redshank, Tringa totanus": "chim choắt chân đỏ",
        "dowitcher": "chim mỏ dài",
        "oystercatcher, oyster catcher": "chim bắt hàu",
        "albatross, mollymawk": "chim hải âu lớn",
        "grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus": "cá voi xám",
        "barracouta, snoek": "cá barracouta",
        "coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch": "cá hồi coho",
        "rock beauty, Holocanthus tricolor": "cá thiên thần sọc vàng",
        "sturgeon": "cá tầm",
        "gar, garfish, garpike, billfish, Lepisosteus osseus": "cá gar",
        "lionfish": "cá sư tử",
    ]
}
